server:
  port: 9999
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: provider_route
          uri: http://localhost:8090
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
#    nacos:
#      discovery:
#        server-addr: localhost:8848